spring:
  application:
    name: TheTodoList
  datasource:
    url: jdbc:mysql://localhost:3306/todoapp?createDatabaseIfNotExist=true
    username: root
    password: "#Onceus1029"
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 10 # 5m
    refreshTokenExpiration: 604800 # 7d